
FROM python:3.10-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir fastapi uvicorn requests pydantic
RUN pip install mcp

EXPOSE 8001

CMD ["uvicorn", "mcp_servers.sec_server:app", "--host", "0.0.0.0", "--port", "8001"]
